name: orphan_hq
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line

  cupertino_icons: ^1.0.6
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.0.11
  path: ^1.9.0
  go_router: ^14.2.0
  uuid: ^4.4.0
  provider: ^6.1.5
  file_picker: ^6.1.1
  shelf: ^1.4.1
  shelf_cors_headers: ^0.1.5
  archive: ^3.4.10
  qr_flutter: ^4.1.0
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true